/**
 * DualModeOscillator UI Component
 *
 * A modular oscillator UI with support for external CV inputs.
 * All knob parameters can receive CV modulation.
 *
 * @module DualModeOscillator/UI
 */

import { SynthKnob, SynthToggle } from '../../VintageSynthUI';
import { SynthRow } from '../../SynthRow';
import type { DualModeOscillatorInputs } from './types';
import { parameterIds, parameters } from './parameters';

export interface DualModeOscillatorProps {
  /** Current parameter values (normalized 0-1 for most) */
  paramValues: Record<string, number>;
  /** Callback when user changes a parameter */
  onChange: (paramId: string, value: number) => void;
  /** External CV inputs that modulate parameters */
  cvInputs?: Partial<DualModeOscillatorInputs>;
  /** Optional parameter prefix for multiple oscillators */
  prefix?: string;
  /** Display label */
  label?: string;
}

/**
 * DualModeOscillator UI - Square/Sawtooth oscillator with PWM
 *
 * Signal Flow:
 * - CV inputs (pitch, pwm, gate) modulate the oscillator
 * - Parameters (waveform, level, octave, etc.) control behavior
 * - Audio output is generated by the WebAudio or JUCE backend
 */
export function DualModeOscillator({
  paramValues,
  onChange,
  cvInputs,
  // prefix is reserved for future multi-oscillator support
  prefix: _prefix = 'osc',
  label = 'OSCILLATOR'
}: DualModeOscillatorProps) {
  void _prefix; // Reserved for multi-instance support
  // Parameter ID helper using standardized IDs
  const getId = (key: keyof typeof parameterIds) => parameterIds[key];

  // Get parameter values with defaults from parameter definitions
  const getParam = (key: keyof typeof parameterIds): number => {
    const id = getId(key);
    const value = paramValues[id];
    const param = parameters[id];
    return value !== undefined ? value : param?.default ?? 0;
  };

  // Check if in square mode (waveform = 0)
  const isSquareMode = getParam('waveform') < 0.5;

  // Octave normalization (maps -4 to 4 -> 0 to 1 for storage)
  const normalizeOctave = (octave: number) => (octave + 4) / 8;
  const denormalizeOctave = (normalized: number) => Math.round(normalized * 8 - 4);

  // Pulse width normalization (0.05-0.95 -> 0-1 for display)
  const normalizePW = (pw: number) => (pw - 0.05) / 0.9;
  const denormalizePW = (normalized: number) => normalized * 0.9 + 0.05;

  // Fine tune normalization (-12 to +12 semitones -> 0-1)
  const normalizeFineTune = (semitones: number) => (semitones + 12) / 24;
  const denormalizeFineTune = (normalized: number) => normalized * 24 - 12;

  // CV indicator styles for knobs receiving external CV
  const getCVIndicator = (hasCV: boolean) => hasCV ? {
    boxShadow: '0 0 8px var(--synth-accent-secondary, #ff0)',
  } : {};

  return (
    <div style={{
      display: 'flex',
      flexDirection: 'column',
      gap: 'var(--synth-space-md)',
      alignItems: 'center',
      padding: 'var(--synth-space-md)',
      background: 'var(--synth-surface-elevated)',
      borderRadius: 'var(--synth-radius-md)',
      border: '1px solid var(--synth-border-subtle)',
    }}>
      {/* Section Label */}
      <div style={{
        color: 'var(--synth-accent-primary)',
        fontSize: 'var(--synth-font-size-base)',
        fontWeight: 'bold',
        letterSpacing: '0.1em'
      }}>
        {label}
      </div>

      {/* CV Input Indicators */}
      {cvInputs && (
        <div style={{
          display: 'flex',
          gap: 'var(--synth-space-sm)',
          fontSize: '9px',
          fontFamily: 'monospace',
          color: 'var(--synth-accent-secondary, #ff0)',
        }}>
          {cvInputs.pitch !== undefined && <span>PITCH CV</span>}
          {cvInputs.pwm !== undefined && <span>PWM CV</span>}
          {cvInputs.gate !== undefined && <span>GATE</span>}
        </div>
      )}

      {/* Row 1: Waveform selector, Level, and Octave */}
      <SynthRow gap="var(--synth-space-lg)">
        <SynthToggle
          label="SAW"
          value={!isSquareMode}
          onChange={(v: boolean) => onChange(getId('waveform'), v ? 1 : 0)}
          variant="toggle"
        />

        <SynthKnob
          label="LEVEL"
          value={getParam('level')}
          onChange={(v: number) => onChange(getId('level'), v)}
          min={0}
          max={1}
        />

        <SynthKnob
          label="OCTAVE"
          value={denormalizeOctave(getParam('octave'))}
          onChange={(v: number) => onChange(getId('octave'), normalizeOctave(v))}
          min={-4}
          max={4}
          step={1}
          options={["128'", "64'", "32'", "16'", "8'", "4'", "2'", "1'", "1/2'"]}
        />
      </SynthRow>

      {/* Row 2: PWM controls and Fine tune */}
      <SynthRow gap="var(--synth-space-lg)">
        <div style={{
          opacity: isSquareMode ? 1 : 0.3,
          pointerEvents: isSquareMode ? 'auto' : 'none',
          transition: 'opacity 0.2s',
          ...getCVIndicator(cvInputs?.pwm !== undefined && isSquareMode),
        }}>
          <SynthKnob
            label="WIDTH"
            value={normalizePW(getParam('pulseWidth'))}
            onChange={(v: number) => onChange(getId('pulseWidth'), denormalizePW(v))}
            min={0}
            max={1}
          />
        </div>

        <div style={{
          opacity: isSquareMode ? 1 : 0.3,
          pointerEvents: isSquareMode ? 'auto' : 'none',
          transition: 'opacity 0.2s'
        }}>
          <SynthKnob
            label="PWM"
            value={getParam('pwmAmount')}
            onChange={(v: number) => onChange(getId('pwmAmount'), v)}
            min={0}
            max={1}
          />
        </div>

        <SynthKnob
          label="FINE"
          value={normalizeFineTune(getParam('fineTune'))}
          onChange={(v: number) => onChange(getId('fineTune'), denormalizeFineTune(v))}
          min={0}
          max={1}
        />
      </SynthRow>

      {/* Status indicator */}
      <div style={{
        color: 'var(--synth-text-tertiary)',
        fontSize: '10px',
        fontFamily: 'monospace',
        display: 'flex',
        gap: 'var(--synth-space-md)',
      }}>
        <span>{isSquareMode ? 'SQUARE' : 'SAW'}</span>
        {isSquareMode && (
          <span>PW: {Math.round(getParam('pulseWidth') * 100)}%</span>
        )}
      </div>
    </div>
  );
}

